ifeq ($(KERNELRELEASE),)
KERNELDIR ?= /lib/modules/$(shell uname -r)/build
PWD := $(shell pwd)
all:                               
	$(MAKE) -C $(KERNELDIR) M=$(PWD) modules
clean:                                             
	$(MAKE) -C $(KERNELDIR) M=$(PWD) clean
else
    obj-m := memdev.o

endif
